language: node_js
node_js:
  - '7.2.1'
cache: yarn

before_script:
  - yarn run lint

before_deploy:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
